-- CreateTable
CREATE TABLE `FileData` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `MsgId` VARCHAR(191) NOT NULL,
    `Size` INTEGER NOT NULL,
    `Name` VARCHAR(191) NOT NULL,
    `Type` VARCHAR(191) NOT NULL,
    `Uploader` VARCHAR(191) NOT NULL,
    `Link` VARCHAR(191) NOT NULL,
    `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `User` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `DCID` VARCHAR(191) NOT NULL,
    `username` VARCHAR(191) NOT NULL,
    `RegisterAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
